name: Dev Build

on:
  push:
    branches: [ "develop", "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          ref: develop
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build --full-stacktrace
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: DevArtifacts
          path: build/libs/*-release.jar
